cluster.name: "cl-elastic-cluster"
node.name: cl-es-node
network.host: [_local_,_site_]
network.publish_host: node_private_ipv4
http.publish_host: node_private_ipv4
transport.publish_host: node_private_ipv4
# Assign these roles for a master eligible node.
node.roles: [ master, data ]

# Only assign the data role for a no master eligible node.
# node.roles: [ data ]

discovery.seed_hosts: ["node_private_ipv4"]
# This setting is only required on the master-eligible node during cluster formation.
# It should be removed after the cluster has been formed.
cluster.initial_master_nodes: ["cl-es-node"]

bootstrap.memory_lock: true

xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/cl-es-node.key
xpack.security.http.ssl.certificate: certs/cl-es-node.crt
xpack.security.http.ssl.certificate_authorities: certs/ca.crt
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/cl-es-node.key
xpack.security.transport.ssl.certificate: certs/cl-es-node.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca.crt
xpack.security.transport.ssl.verification_mode: certificate
xpack.monitoring.collection.enabled: true