cluster.name: "elastic-cluster"
#node.name: node-1
network.host: 0.0.0.0
discovery.type: single-node
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true
#discovery.seed_providers: ec2
#discovery.ec2.tag.role: esnode
#cloud.node.auto_attributes: true
#cluster.routing.allocation.awareness.attributes: aws_availability_zone


